### ISSUE TITLE
Stream cinema raises exception at the startup

### ISSUE THREAD

**Issue by olii** [mx3L/archivczsk-doplnky#13]
## Issue
Stream cinema plugin crashes at the startup running on clean OpenPli 6.2. It is caused(probably) because of missing attribute `quality` in plugin config.

## Log
```
22:25:26.220 [ERROR] Addon get_content error cb.
[Failure instance: Traceback: <type 'exceptions.AttributeError'>: quality
/usr/lib/python2.7/threading.py:774:__bootstrap
/usr/lib/python2.7/threading.py:801:__bootstrap_inner
--- <exception caught here> ---
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/task.py:69:run
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/contentprovider.py:727:run_script
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.stream-cinema/default.py:86:<module>
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/addon.py:135:getSetting
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/addon.py:84:get_setting
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/addon.py:373:get_setting
/usr/lib/enigma2/python/Components/config.py:1666:__getattr__
]
22:25:26.236 [ERROR] Addon error.
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/exception.py", line 54, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/handlers/addon.py", line 37, in open_item_error_cb
    failure.raiseException()
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/task.py", line 69, in run
    result = function(*args, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/contentprovider.py", line 727, in run_script
    'sys':self.__addon_sys, 'os':os})
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.stream-cinema/default.py", line 86, in <module>
    settings = {'quality':__addon__.getSetting('quality')}
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/addon.py", line 135, in getSetting
    val = self._addon.get_setting(setting)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/addon.py", line 84, in get_setting
    return self.settings.get_setting(setting_id)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/addon.py", line 373, in get_setting
    setting = getattr(self.main, '%s' % setting_id)
  File "/usr/lib/enigma2/python/Components/config.py", line 1666, in __getattr__
AttributeError: quality
```

## Steps to reproduce
* Install clean enigma2 image.
* Install archiveCZSK plugin.
* Update stream cinema plugin.
* Open stream cinema.
* `Autor musi aktualizovat plugin` is shown on the screen.

**Comment by mtester270** [comment]
S tou anglictinou si robis prdel alebo to myslis vazne?

Zaujimalo by ma aku verziu archivu pouzivas?
(Which version of plugin archivczsk are you using?)

**Comment by olii** [comment]
Zdravim, 
na anglictinu som zvyknuty, hlavne ked pisem na bugtracker. Commit messages v tomto repe su tiez v anglictine.

K tvojej otazke:
```
root@dm8000:~# grep version /usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/version.py
version = "1.0.7"

root@dm8000:~# grep version /usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/xbmc_doplnky/plugin.video.stream-cinema/addon.xml
<addon id="plugin.video.stream-cinema" name="Stream Cinema" provider-name="chaoss (origin bbaron)" version="1.3.3">
        <import addon="xbmc.python" version="2.1.0" />
        <import addon="script.module.stream.resolver" version="1.6.25" />
```

**Comment by mtester270** [comment]
No to je zase problem tych vasich openXXX (pli, atv) systemov kde vo verzii 6.2 tam nieco dojubali asi ale skumat to fakt nebudem. Chcem tam spravit nejake upravy tak toto opravim ked si to tak nadstandardne opisal (termin ti nepoviem kedze mi za to nik neplati a neviem kedy si spravim cas a naladu). Hned bolo jasne ze asi si nikdy nerobil testera :-D

K tvojmu dotazu: to ze cely kod je v anglictine je standard (videl si kod v slovencine? Cisty grcc) ale neznamena to ze sa musime bavit anglicky a este ked sa bavime o CZ SK plugine  ze jo :-)

**Comment by mtester270** [comment]
pokus cislo 2 na test
[archivCZSK.zip](https://github.com/mx3L/archivczsk-doplnky/files/2048248/archivCZSK.zip)

**Comment by olii** [comment]
Momentalne sa tomu nemozem venovat, dufam ze tento tyzden sa k tomu uz dostanem ..

**Comment by mtester270** [comment]
tak snad uz posledny pokus 💃 (udajne uspesny, takze treba si pockat na novu verziu archivu 1.1.0)
[archivCZSK.zip](https://github.com/mx3L/archivczsk-doplnky/files/2053496/archivCZSK.zip)

**Comment by Pr0metheus2** [comment]
Odskusam aj ja, kazdopadne dakujeme za snahu problem riesit

**Comment by Pr0metheus2** [comment]
Oprava funkcna, velka vdaka.
