### ISSUE TITLE
Nefunkční plugin Eurosport Player

### ISSUE THREAD

**Issue by dpuhr** [mx3L/archivczsk-doplnky#50]
cookie uložena na svém místě, ale plugin hlásí chybu:

```
root@vuzero4k:/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/data/plugin.video.eurosport# ls -l
-rw-r--r--    1 root     root           281 Jan 18 14:43 cookie
root@vuzero4k:/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/data/plugin.video.eurosport# tail -f /tmp/archivCZSK.log 
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
  File "/usr/lib/python2.7/httplib.py", line 1082, in request
  File "/usr/lib/python2.7/httplib.py", line 1121, in _send_request
  File "/usr/lib/python2.7/httplib.py", line 1060, in putheader
ValueError: Invalid header value 'st=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU0VSSUQ6ZXVyb3Nwb3J0OmY0OWM4NzFmLWJmZGQtNGVjNi04YjUyLTNjMzg0NjQzZTI2NCIsImp0aSI6InRva2VuLTQ0MTM5MTk1LTUyYjUtNGMwNy1iOWYwLTk1YTc2YmU5YzQ0OSIsImFub255bW91cyI6ZmFsc2UsImlhdCI6MTY0MjQxMTM3OH0.F1QRVlku3U0VpzE-6t0OemCKquu6Ubvo2FXvg4*****\n'

2022-01-18 14:52:47,887 - INFO - VideoAddonContentProvider(VideoAddon(Eurosport Player-1.3)) trying to resolve dependencies for VideoAddon(Eurosport Player-1.3)
2022-01-18 14:52:47,887 - INFO - VideoAddonContentProvider(VideoAddon(Eurosport Player-1.3)) requires script.module.stream.resolver addon, version 1.6.22
2022-01-18 14:52:47,888 - INFO - VideoAddonContentProvider(VideoAddon(Eurosport Player-1.3)) get_content - params: {}
2022-01-18 14:52:47,911 - INFO - VideoAddonContentProvider(VideoAddon(Eurosport Player-1.3)) get_content_cb - success: False, items: 1, guicmd: None - {}
2022-01-18 14:52:47,912 - ERROR - Addon get_content error cb.
[Failure instance: Traceback: <type 'exceptions.ValueError'>: Invalid header value 'st=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU0VSSUQ6ZXVyb3Nwb3J0OmY0OWM4NzFmLWJmZGQtNGVjNi04YjUyLTNjMzg0NjQzZTI2NCIsImp0aSI6InRva2VuLTQ0MTM5MTk1LTUyYjUtNGMwNy1iOWYwLTk1YTc2YmU5YzQ0OSIsImFub255bW91cyI6ZmFsc2UsImlhdCI6MTY0MjQxMTM3OH0.F1QRVlku3U0VpzE-6t0OemCKquu6Ubvo2FXvg4*****\n'
/usr/lib/python2.7/threading.py:774:__bootstrap
/usr/lib/python2.7/threading.py:801:__bootstrap_inner
--- <exception caught here> ---
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/task.py:69:run
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/contentprovider.py:803:run_script
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/addons/plugin.video.eurosport/default.py:279:<module>
<string>:59:run
<string>:160:root
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/addons/plugin.video.eurosport/default.py:148:categories
<string>:103:request
/usr/lib/python2.7/urllib2.py:154:urlopen
/usr/lib/python2.7/urllib2.py:429:open
/usr/lib/python2.7/urllib2.py:447:_open
/usr/lib/python2.7/urllib2.py:407:_call_chain
/usr/lib/python2.7/urllib2.py:1241:https_open
/usr/lib/python2.7/urllib2.py:1195:do_open
/usr/lib/python2.7/httplib.py:1082:request
/usr/lib/python2.7/httplib.py:1121:_send_request
/usr/lib/python2.7/httplib.py:1060:putheader
]
2022-01-18 14:52:47,916 - ERROR - Addon error.
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/exception.py", line 55, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/handlers/addon.py", line 78, in open_item_error_cb
    failure.raiseException()
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/task.py", line 69, in run
    result = function(*args, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/contentprovider.py", line 803, in run_script
    'sys':self.__addon_sys, 'os':os})
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/addons/plugin.video.eurosport/default.py", line 279, in <module>
    xbmcprovider.XBMCMultiResolverContentProvider(provider, settings, __addon__, session).run(params)
  File "<string>", line 59, in run
  File "<string>", line 160, in root
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/addons/plugin.video.eurosport/default.py", line 148, in categories
    self.data = util.request(self.base_url+'cms/routes/home?include=default&decorators=viewingHistory,isFavorite,playbackAllowed&page[items.number]=1&page[items.size]=8', headers=self.headers)
  File "<string>", line 103, in request
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
  File "/usr/lib/python2.7/httplib.py", line 1082, in request
  File "/usr/lib/python2.7/httplib.py", line 1121, in _send_request
  File "/usr/lib/python2.7/httplib.py", line 1060, in putheader
ValueError: Invalid header value 'st=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJVU0VSSUQ6ZXVyb3Nwb3J0OmY0OWM4NzFmLWJmZGQtNGVjNi04YjUyLTNjMzg0NjQzZTI2NCIsImp0aSI6InRva2VuLTQ0MTM5MTk1LTUyYjUtNGMwNy1iOWYwLTk1YTc2YmU5YzQ0OSIsImFub255bW91cyI6ZmFsc2UsImlhdCI6MTY0MjQxMTM3OH0.F1QRVlku3U0VpzE-6t0OemCKquu6Ubvo2FXvg4*****\n'
```

**Comment by misanov** [comment]
Soubor cookie musí obsahovat přesně jen ten řetězec z cookie st, máte tam přidaný Enter na konci "\n"

**Comment by dpuhr** [comment]
Newline ve vi nebyla vidět. Odstranil jsem, cookie by měla být v pořádku.
Před chvílí se updatnul Eurosport Player plugin. Po restartu takto:

```
root@vuzero4k:/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/data/plugin.video.eurosport# tail -f /tmp/archivCZSK.log 
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/contentprovider.py", line 803, in run_script
    'sys':self.__addon_sys, 'os':os})
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/addons/plugin.video.eurosport/default.py", line 279, in <module>
    xbmcprovider.XBMCMultiResolverContentProvider(provider, settings, __addon__, session).run(params)
  File "<string>", line 59, in run
  File "<string>", line 160, in root
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/addons/plugin.video.eurosport/default.py", line 153, in categories
    if not is_now(item['attributes']['scheduleStart'], item['attributes']['scheduleEnd']): continue
KeyError: 'scheduleStart'

2022-01-20 12:24:03,822 - INFO - VideoAddonContentProvider(VideoAddon(Eurosport Player-1.4)) trying to resolve dependencies for VideoAddon(Eurosport Player-1.4)
2022-01-20 12:24:03,823 - INFO - VideoAddonContentProvider(VideoAddon(Eurosport Player-1.4)) requires script.module.stream.resolver addon, version 1.6.22
2022-01-20 12:24:03,824 - INFO - VideoAddonContentProvider(VideoAddon(Eurosport Player-1.4)) get_content - params: {}
2022-01-20 12:24:04,629 - INFO - VideoAddonContentProvider(VideoAddon(Eurosport Player-1.4)) get_content_cb - success: False, items: 1, guicmd: None - {}
2022-01-20 12:24:04,632 - ERROR - Addon get_content error cb.
[Failure instance: Traceback: <type 'exceptions.KeyError'>: 'scheduleStart'
/usr/lib/python2.7/threading.py:774:__bootstrap
/usr/lib/python2.7/threading.py:801:__bootstrap_inner
--- <exception caught here> ---
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/task.py:69:run
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/contentprovider.py:803:run_script
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/addons/plugin.video.eurosport/default.py:279:<module>
<string>:59:run
<string>:160:root
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/addons/plugin.video.eurosport/default.py:153:categories
]
2022-01-20 12:24:04,638 - ERROR - Addon error.
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/gui/exception.py", line 55, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/handlers/addon.py", line 78, in open_item_error_cb
    failure.raiseException()
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/tools/task.py", line 69, in run
    result = function(*args, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/engine/contentprovider.py", line 803, in run_script
    'sys':self.__addon_sys, 'os':os})
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/addons/plugin.video.eurosport/default.py", line 279, in <module>
    xbmcprovider.XBMCMultiResolverContentProvider(provider, settings, __addon__, session).run(params)
  File "<string>", line 59, in run
  File "<string>", line 160, in root
  File "/usr/lib/enigma2/python/Plugins/Extensions/archivCZSK/resources/repositories/addons/plugin.video.eurosport/default.py", line 153, in categories
    if not is_now(item['attributes']['scheduleStart'], item['attributes']['scheduleEnd']): continue
KeyError: 'scheduleStart'
```

Vidím v logu
```
requires script.module.stream.resolver addon, version 1.6.22
```
Je potřeba něco doinstalovat?
Mám čerstvě přeinstalovaný OpenATV 6.4, verze z 15.1.2022, HW mám VU+Zero 4K

Díky!

**Comment by dpuhr** [comment]
Po další aktualizaci už to chodí. Díky ;)

**Comment by misanov** [comment]
Ne, to byla chyba teď co je tenis, mají tam zmatečná data na hp, tak jsem to upravil.
